"use client"

import { motion } from "framer-motion"
import { Scale, Shield, FileText, AlertCircle } from "lucide-react"

export function TermsContent() {
  return (
    <div className="bg-background">
      {/* Background Pattern */}
      <div className="fixed inset-0 -z-10 bg-[url('/subtle-parchment-texture.png')] opacity-5" />

      <div className="container mx-auto px-4 py-16 max-w-4xl">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <div className="flex justify-center mb-6">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10">
              <Scale className="h-8 w-8 text-primary" />
            </div>
          </div>
          <h1 className="font-serif text-4xl font-bold text-foreground mb-4">
            Terms and Conditions
          </h1>
          <p className="text-muted-foreground">
            Last Updated: December 09, 2025
          </p>
          <div className="mt-6 p-4 bg-amber-500/10 border border-amber-500/20 rounded-lg">
            <p className="text-sm text-amber-900 dark:text-amber-200 flex items-center justify-center gap-2">
              <AlertCircle className="h-4 w-4" />
              PLEASE READ THESE TERMS CAREFULLY. BY USING THE PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS.
            </p>
          </div>
        </motion.div>

        {/* Content */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="prose prose-slate dark:prose-invert max-w-none"
        >
          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4 flex items-center gap-2">
              <FileText className="h-6 w-6 text-primary" />
              1. INTRODUCTION AND ACCEPTANCE
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>1.1. The Contract:</strong> These Terms and Conditions (hereinafter "Terms") govern your access to and use of the website judiciallegalways.com, its mobile applications, and its digital ecosystem (collectively, the "Platform"), operated by Judicially Legal Ways (hereinafter "Company," "we," "us," or "our").
              </p>
              <p>
                <strong>1.2. Electronic Record:</strong> This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder. It is generated by a computer system and does not require physical or digital signatures.
              </p>
              <p>
                <strong>1.3. Modification:</strong> We reserve the right to modify these Terms at any time to reflect changes in the law, our platform optimization, or technical upgrades. Your continued use of the Platform after such changes constitutes acceptance of the new Terms.
              </p>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4 flex items-center gap-2">
              <Shield className="h-6 w-6 text-primary" />
              2. USER ELIGIBILITY AND ACCOUNT SECURITY
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>2.1. Competency:</strong> You must be at least 18 years of age and competent to contract under the Indian Contract Act, 1872. If you are a minor (e.g., a CLAT aspirant under 18), you may use the Platform only with the involvement and consent of a parent or legal guardian.
              </p>
              <p>
                <strong>2.2. User Personas:</strong> The Platform caters to distinct user roles including Law Students, Advocates, and Researchers. You agree to provide accurate professional details (e.g., Bar Council Enrollment Number, University Name) during registration to access role-specific features.
              </p>
              <p>
                <strong>2.3. Account Security (Supabase Auth):</strong>
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Credentials:</strong> You are responsible for maintaining the confidentiality of your login credentials (Email/Password).</li>
                <li><strong>No Sharing:</strong> Your account is a single-user license. Sharing credentials with other individuals is strictly prohibited and constitutes a material breach of these Terms.</li>
                <li><strong>Device Tracking:</strong> To prevent unauthorized access and piracy, the Platform employs IP/device tracking and session management technologies. We reserve the right to limit the number of simultaneous active sessions or registered devices associated with your account.</li>
                <li><strong>Suspicious Activity:</strong> If our system detects simultaneous logins from geographically disparate IP addresses or abnormal activity patterns, your account may be automatically suspended pending verification.</li>
              </ul>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
              3. INTELLECTUAL PROPERTY AND DRM ENFORCEMENT
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>3.1. Proprietary Content:</strong> All content hosted on the Platform, including but not limited to case studies, judgment breakdowns, subject notes, quizzes, the "Secure DRM-Based Reader" interface, and the underlying code (React/Next.js), is the exclusive property of the Company and is protected by Indian copyright laws.
              </p>
              <p>
                <strong>3.2. Limited License:</strong> We grant you a limited, non-exclusive, non-transferable, revocable license to access and view the Content solely for personal, educational, and professional research purposes. This license does not convey any rights of ownership.
              </p>
              <p>
                <strong>3.3. Strict DRM Restrictions:</strong> The Platform utilizes enterprise-level Digital Rights Management (DRM) to protect its assets. You explicitly agree to the following prohibitions:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>No Downloading:</strong> You shall not attempt to download, save, scrape, or archive any content for offline use, except where an "Offline Mode" is explicitly provided within the secure app environment.</li>
                <li><strong>No Copy-Paste:</strong> You acknowledge that the "Copy" and "Paste" functionalities are disabled within the Reader to prevent extraction. You shall not attempt to bypass this restriction via browser extensions or scripts.</li>
                <li><strong>No Screen Recording:</strong> The use of screen recording software, screen capture tools, external cameras, or any mechanism to record the visual display of the Platform is strictly prohibited. The Platform employs front-end detection logic; attempts to engage screen recording may result in the automatic blacking out of the content or immediate termination of your session.</li>
                <li><strong>No Reverse Engineering:</strong> You shall not decompile, reverse engineer, decrypt, or attempt to derive the source code of the Obfuscated DOM content or the encrypted rendering engine.</li>
              </ul>
              <p>
                <strong>3.4. Dynamic Watermarking Consent:</strong> You acknowledge and consent that all Content displayed to you will be overlaid with a Dynamic Watermark, which may include your Name, User ID, IP address, device information, and timestamp. This watermark is a security feature designed to deter and trace unauthorized distribution. You agree not to obscure, remove, or tamper with this watermark.
              </p>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
              4. COURT UPDATES AND DATA DISCLAIMER
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>4.1. Aggregator Role:</strong> The Court Updates & Tracking System aggregates data from public records, the National Judicial Data Grid (NJDG), and third-party sources. The Platform acts solely as an intermediary for this information.
              </p>
              <p>
                <strong>4.2. No Warranty of Accuracy:</strong> While we aim for "Real-time" updates, we do not guarantee the absolute accuracy, completeness, or currency of judicial data (Cause Lists, Hearing Schedules, Orders).
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Official Sources Prevail:</strong> In the event of any discrepancy between the data on the Platform and the official records of the Supreme Court, High Courts, or District Courts, the official records shall prevail.</li>
              </ul>
              <p>
                <strong>4.3. Limitation of Liability for Professional Use:</strong>
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Not Legal Advice:</strong> The Platform provides educational summaries and tracking tools. It does not constitute legal advice or a substitute for professional legal research using certified copies.</li>
                <li><strong>No Professional Negligence:</strong> The Company shall not be liable for any missed hearings, default orders, or professional negligence claims arising from your reliance on the Platform's tracking system. Advocates are advised to cross-verify all hearing dates with the official eCourts services.</li>
              </ul>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
              5. PAYMENTS, SUBSCRIPTIONS, AND REFUNDS
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>5.1. Payment Processing:</strong> Payments for subscriptions and case bundles are processed via third-party gateways (Razorpay/Stripe). You agree to their terms of service regarding transaction security.
              </p>
              <p>
                <strong>5.2. GST Compliance:</strong> You are responsible for providing a valid GSTIN at the time of purchase if you intend to claim input tax credit. Invoices will be generated automatically based on the details provided.
              </p>
              <p>
                <strong>5.3. No Refund Policy:</strong>
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Digital Goods:</strong> Due to the nature of digital content, which is instantly accessible and consumable, all sales are final and non-refundable. We do not offer refunds for "change of mind" or "incorrect purchase."</li>
                <li><strong>Subscription Renewal:</strong> Subscriptions automatically renew unless cancelled. You must cancel before the renewal date to avoid future charges. No pro-rata refunds are issued for mid-cycle cancellations.</li>
              </ul>
              <p>
                <strong>5.4. Defective Service Exception:</strong> A refund may be considered, at our sole discretion, only if:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>A technical error (e.g., double debit) occurred during the transaction.</li>
                <li>The Platform remains inaccessible for a continuous period exceeding 48 hours due to server failure, preventing you from accessing paid content.</li>
              </ul>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
              6. USER CONDUCT AND TERMINATION
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>6.1. Prohibited Activities:</strong> You agree not to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Use any "robot," "spider," or other automatic device to scrape court data or content.</li>
                <li>Share your account credentials with peers or on public forums.</li>
                <li>Post defamatory, obscene, or illegal content in any future community forums.</li>
              </ul>
              <p>
                <strong>6.2. Termination:</strong> We reserve the right to suspend or terminate your account immediately, without notice or refund, if:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Our systems detect screen recording or piracy attempts.</li>
                <li>You breach the concurrent session limits.</li>
                <li>You violate any provision of these Terms.</li>
              </ul>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
              7. LIMITATION OF LIABILITY AND INDEMNITY
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>7.1. Cap on Liability:</strong> To the maximum extent permitted by Indian law, the Company's total liability for any claim arising out of or relating to these Terms or the Platform shall be limited to the amount you paid to us in the six (6) months preceding the event giving rise to the claim.
              </p>
              <p>
                <strong>7.2. Indirect Damages:</strong> We shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, loss of data, loss of goodwill, or failure in examinations (for students) or litigation outcomes (for advocates).
              </p>
              <p>
                <strong>7.3. Indemnity:</strong> You agree to indemnify and hold harmless the Company, its directors, and affiliates from any claims, damages, or expenses arising from your violation of these Terms or your infringement of any intellectual property rights.
              </p>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
              8. DISPUTE RESOLUTION AND JURISDICTION
            </h2>
            <div className="space-y-4 text-muted-foreground">
              <p>
                <strong>8.1. Governing Law:</strong> These Terms shall be governed by the laws of India.
              </p>
              <p>
                <strong>8.2. Arbitration:</strong> Any dispute shall be referred to a sole arbitrator appointed by the Company, with the seat of arbitration in India.
              </p>
              <p>
                <strong>8.3. Jurisdiction:</strong> Subject to arbitration, the courts in India shall have exclusive jurisdiction.
              </p>
            </div>
          </section>

          <div className="mt-12 p-6 bg-muted rounded-lg border">
            <p className="text-sm text-muted-foreground text-center">
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:juidiciallegalways@gmail.com" className="text-primary hover:underline">
                juidiciallegalways@gmail.com
              </a>
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  )
}
